/*
   The MIT License (MIT)
   Copyright (c) 2019 Techno Road Inc.
   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:
   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.
   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE.
 */
#include <chrono>
#include <iostream>

#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/imu.hpp>
#include <tf2_ros/transform_broadcaster.h>
#include <tf2_msgs/msg/tf_message.hpp>
#include <tf2_geometry_msgs/tf2_geometry_msgs.h> // for use tf2::Quaternion
// #include <diagnostic_updater/diagnostic_updater.hpp>

#include "RTIMULib.h"


using namespace std::chrono_literals;

class ImuNode : public rclcpp::Node {
public:

  explicit ImuNode(const rclcpp::NodeOptions& op)
    : Node("imu", op) {
    // std::cout << "Inizializing" << "\n";
    RCLCPP_INFO(this->get_logger(), "Inizializing");

    int x = init3();


    timer_ = this->create_wall_timer(
      500ms, std::bind(&ImuNode::Spin, this));
  }

  ~ImuNode() {
    RCLCPP_INFO(this->get_logger(), "called destructor!");

    // imu_.Close();
  }

private:

  RTIMUSettings *settings = new RTIMUSettings("RTIMULib");

  RTIMU *imu = RTIMU::createIMU(settings);

  rclcpp::TimerBase::SharedPtr timer_;
  rclcpp::Publisher<sensor_msgs::msg::Imu>::SharedPtr imu_data_pub_;
  rclcpp::Publisher<tf2_msgs::msg::TFMessage>::SharedPtr tf_br_;
  int init3() {
    int sampleCount = 0;
    int sampleRate  = 0;
    uint64_t rateTimer;
    uint64_t displayTimer;
    uint64_t now;

    //  Using RTIMULib here allows it to use the .ini file generated by
    // RTIMULibDemo.
    //  Or, you can create the .ini in some other directory by using:
    //      RTIMUSettings *settings = new RTIMUSettings("<directory path>",
    // "RTIMULib");
    //  where <directory path> is the path to where the .ini file is to be
    // loaded/saved


    if ((imu == NULL) || (imu->IMUType() == RTIMU_TYPE_NULL)) {
      printf("No IMU found\n");
      exit(1);
    }

    //  This is an opportunity to manually override any settings before the call
    // IMUInit

    //  set up IMU

    imu->IMUInit();

    //  this is a convenient place to change fusion parameters

    imu->setSlerpPower(0.02);
    imu->setGyroEnable(true);
    imu->setAccelEnable(true);
    imu->setCompassEnable(true);

    //  set up for rate timer

    rateTimer = displayTimer = RTMath::currentUSecsSinceEpoch();

    // This is for testing ==0 means it iwll never execute
    while (1 == 0) {
      //  poll at the rate recommended by the IMU

      usleep(imu->IMUGetPollInterval() * 1000);

      while (imu->IMURead()) {
        RTIMU_DATA imuData = imu->getIMUData();

        //  add the pressure data to the structure


        sampleCount++;

        now = RTMath::currentUSecsSinceEpoch();

        //  display 10 times per second

        if ((now - displayTimer) > 10) {
          printf("Sample rate %d (cycle %d): %s\n", sampleRate,
                 (now - displayTimer) / 1000,
                 RTMath::displayDegrees("", imuData.fusionPose));


          fflush(stdout);
          displayTimer = now;
        }

        //  update rate every second

        if ((now - rateTimer) > 1000000) {
          sampleRate  = sampleCount;
          sampleCount = 0;
          rateTimer   = now;
        }
      }
    }

    // printf("Var %d \n", p);
    return 0;
  }

  int  InitParam() {}

  void PubImuData() {
    usleep(imu->IMUGetPollInterval() * 1000);

    while (imu->IMURead()) {
      RTIMU_DATA imuData = imu->getIMUData();

      //  add the pressure data to the structure


      //  display 10 times per second


      printf("%s\n",
             RTMath::displayDegrees("", imuData.fusionPose));


      fflush(stdout);
    }
  }

  void Spin() {
    RCLCPP_INFO(this->get_logger(), "Publishing data");

    PubImuData();
  }
}; // end of class


int main(int argc, char **argv) {
  rclcpp::init(argc, argv);

  rclcpp::NodeOptions options;
  options.allow_undeclared_parameters(true);
  options.automatically_declare_parameters_from_overrides(true);

  auto imu_node = std::make_shared<ImuNode>(options);

  rclcpp::spin(imu_node);
  rclcpp::shutdown();
  return 0;
}
