#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'ros2-rtimulib==1.1.3','console_scripts','imu_node'
__requires__ = 'ros2-rtimulib==1.1.3'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ros2-rtimulib==1.1.3', 'console_scripts', 'imu_node')()
    )
