#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'jetbot-oled-display==1.0.0','console_scripts','ros2_jetbot_oled_display'
__requires__ = 'jetbot-oled-display==1.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('jetbot-oled-display==1.0.0', 'console_scripts', 'ros2_jetbot_oled_display')()
    )
